<a href="https://colab.research.google.com/github/parxpa1/programacion1/blob/main/parcial%2C%20programacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PARCIAL DE PROGRAMACION:**

codigo de ayuda:
# CREAR UN CSV:
from google.colab import files
import csv
datos = [
    ["Nombre", "Edad", "Ciudad"],
    ["Ana", 25, "Bogotá"],
    ["Luis", 30, "Medellín"],
    ["Carlos", 28, "Cali"]
]

with open("datos.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(datos)

files.download("datos.csv")

# CREAR MODULOS Y PAQUETES:

import os
os.makedirs("op", exist_ok=True)

%%writefile op/operaciones.py

# FUNCION LAMBDA
import pandas as pd
x = [1, 2, 3, 4]
x = pd.DataFrame(x)
normalizar = lambda x: (x - x.mean()) / x.std()
resultado = normalizar(x)
print(resultado)


In [2]:
import numpy as np


In [10]:
np.random.seed(0)
datos = np.random.randint(191, 197, 50)
datos

array([195, 196, 191, 194, 194, 194, 192, 194, 196, 193, 195, 191, 191,
       195, 193, 192, 191, 192, 196, 192, 196, 191, 192, 195, 194, 191,
       194, 196, 191, 193, 194, 191, 192, 194, 196, 194, 194, 191, 192,
       192, 192, 191, 193, 195, 194, 194, 193, 195, 193, 191])

1. Implemente una filtración sobre el elemento datos e imprima el elemento con los valores resultantes.

In [22]:
datos[ datos > 194]

array([195, 196, 196, 195, 195, 196, 196, 195, 196, 196, 195, 195])

este codigo muestra a todos los valores con la condicion pedida, en este caso seria, mayores a 194

2. Escale cada uno de los valores de datos utilizando una función lambda:
𝑥􀯜 − 𝑥̅
𝑆􀯫
Para 𝑥̅ la media aritmética y 𝑆􀯫 la desviación estándar.

In [109]:
normalizar = lambda datos:(datos - datos.mean()) / datos.std()
normalizar(datos)

array([ 1.0615568 ,  1.65793702, -1.32396409,  0.46517657,  0.46517657,
        0.46517657, -0.72758387,  0.46517657,  1.65793702, -0.13120365,
        1.0615568 , -1.32396409, -1.32396409,  1.0615568 , -0.13120365,
       -0.72758387, -1.32396409, -0.72758387,  1.65793702, -0.72758387,
        1.65793702, -1.32396409, -0.72758387,  1.0615568 ,  0.46517657,
       -1.32396409,  0.46517657,  1.65793702, -1.32396409, -0.13120365,
        0.46517657, -1.32396409, -0.72758387,  0.46517657,  1.65793702,
        0.46517657,  0.46517657, -1.32396409, -0.72758387, -0.72758387,
       -0.72758387, -1.32396409, -0.13120365,  1.0615568 ,  0.46517657,
        0.46517657, -0.13120365,  1.0615568 , -0.13120365, -1.32396409])

4. Convierta el elemento datos en un DataFrame usando pandas. Imprima el elemento.

In [115]:
import pandas as pd
df= pd.DataFrame(datos)
df

,datos1,datos2
0,7.180748,6.861376
1,7.701062,6.471774
2,7.271689,6.362365
3,6.720308,6.838444
4,7.015700,7.472108
5,6.390949,7.069059
6,7.293283,7.008203
7,7.009625,7.039661
8,6.959129,6.953915
9,7.007488,7.124110


3. Implemente el método .describe() e interprete los resultados.

In [114]:
df.describe()

,datos1,datos2
count,58.000000,58.000000
mean,7.064586,6.971736
std,0.351427,0.392418
min,6.345376,6.305708
25%,6.790062,6.679989
50%,7.014305,6.953625
75%,7.287884,7.147781
max,7.929321,7.978883


count: es la cantidad de elementos.
mean: es el promedio.
std:es la variacion.
min:es el valor minimo que hay entre los elementos.
X%: indica a que cantidad supera entre todos los valores.
max: indica cual es el elemento de mayor valor.

5. Exporte los resultados a un archivo CSV llamado resultados.csv

In [168]:
from google.colab import files
import csv
p = df
with open("resultados.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(p)

files.download("resultados.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
Instrucción 2: Construya un DataFrame en pandas con información de su elección. El
DataFrame debe cumplir con: (1) al menos 4 columnas (por ejemplo: nombre, edad, ingreso,
ciudad), (2) al menos 5 filas (registros) y (3) incluir datos numéricos y categóricos (o variable
cualitativa)

In [48]:
import pandas as pd

In [130]:
df1 = pd.DataFrame({"nombre":["juan","jhon","sara","vale","alli"], "edad":[17,18,19,20,25],"genero":["h","h","m","m","m"],"ciudad":["bucaramanga","cucuta","bucaramanga","bucaramanga","bucaramanga"]})
df1

,nombre,edad,genero,ciudad
0,juan,17,h,bucaramanga
1,jhon,18,h,cucuta
2,sara,19,m,bucaramanga
3,vale,20,m,bucaramanga
4,alli,25,m,bucaramanga


1. Muestre las primeras filas usando método .head()

In [131]:
df1.head(1)

,nombre,edad,genero,ciudad
0,juan,17,h,bucaramanga


2. Seleccione una columna específica de su elección.

In [132]:
df1["edad"]

,edad
0,17
1,18
2,19
3,20
4,25


3. Seleccione un conjunto de filas dadas condiciones específicas sobre valores de la columna.

In [134]:
df1.loc[df1["genero"]== "h"]

,nombre,edad,genero,ciudad
0,juan,17,h,bucaramanga
1,jhon,18,h,cucuta


4. Cree una nueva columna que represente una transformación de una variable.

In [140]:
df1["ciudad"] = df1["nacio en bucaramanga"] = df1["ciudad"] == "bucaramanga"
df1

,nombre,edad,genero,ciudad,ciudad_codigo,nacio en bucaramanga
0,juan,17,h,True,0,True
1,jhon,18,h,False,1,False
2,sara,19,m,True,0,True
3,vale,20,m,True,0,True
4,alli,25,m,True,0,True


5. Agrupe los datos por una variable categórica usando el método .groupby(). Por ejemplo:
# Agrupar por ciudad y calcular ingreso promedio
grupo = df.groupby("Ciudad")["Ingreso"].mean()

In [78]:
grupo= df.groupby("nombre")["edad"].mean()
grupo

,edad
nombre,
alli,25.0
jhon,18.0
juan,17.0
sara,19.0
vale,20.0


6. Exporte el DataFrame final a un archivo CSV llamado datos_procesados.csv

In [142]:
from google.colab import files
import csv
datos = df1

with open("datos.csv", "w", newline="") as f:
  writer = csv.writer(f)
  writer.writerows(datos)

files.download("datos.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Parte III: Salidas de instrucciones no asignadas (33/100): Realice el siguiente programa en
lenguaje Python. Ejecute los códigos y registre los resultados obtenidos en el mismo archivo
.ipynb de la parte II. Posteriormente, cree el enlace de su repositorio en GitHub, cópielo y
péguelo en un archivo PDF. Finalmente, cargue este PDF junto con los archivos generados en la
parte II.

Proyecto: Una institución educativa busca analizar el desempeño académico de un mismo
grupo de estudiantes en dos evaluaciones distintas. Se plantea la posibilidad de que existan
diferencias en las calificaciones promedio entre ambas pruebas. Con este propósito, se requiere
desarrollar un paquete que permita realizar la comparación de los resultados para cualquier
conjunto de estudiantes.
1. Genere dos muestras aleatorias de tamaño 5W, donde W corresponden al último dígito del
día de cumpleaños:
 Prueba A: distribución normal con media 7.2 y desviación estándar 0.4
 Prueba B: distribución Gamma con forma 306 y escala 0.0229
np.random.gamma(shape=306, scale=0.0229, size=5W)

In [104]:
datos1=np.random.normal(loc=7.2, scale=0.4, size=58)
datos2=np.random.gamma(shape=306, scale=0.0229, size=58)
print("datos1:",datos1)
print("datos2:",datos2)

datos1: [7.7297435  7.13111968 7.49214072 7.64183139 6.79406964 6.95906726
 7.56856336 7.38432579 7.56951862 7.14697279 7.08439792 6.40054421
 6.74159983 7.21882644 7.52982289 7.41247135 7.14870321 7.09129137
 7.28687185 7.23128447 7.76181821 7.25857631 6.60750162 6.69097675
 7.80750373 6.73153582 7.50579898 7.09265091 7.13209668 7.14634689
 7.68855398 7.12286327 7.18667229 6.5876786  7.2826762  7.412417
 7.29565823 7.7591585  7.22206854 7.31959098 7.8594016  6.57999432
 7.01766986 7.7704635  7.57445166 7.47135204 7.5330603  7.33082648
 7.85263897 7.35110367 7.29594684 7.26358347 7.27714558 6.73719309
 7.50826922 7.14782411 7.92876604 7.16973981]
datos2: [7.16964497 7.09896326 7.79053229 6.99385201 6.26913171 6.92881702
 7.39121771 6.83433436 6.88951948 7.45945357 6.93054668 6.79754631
 7.57221955 7.42345504 6.22477597 7.23852965 6.64698706 6.2429905
 6.5535754  6.52472956 7.35429453 6.65410638 7.21680823 7.16304723
 7.07669763 7.35824655 7.30515882 7.22759792 7.10146977 6.83767804
 6.

2. Construya un DataFrame en pandas que contenga ambas muestras.

In [92]:
df= pd.DataFrame({"datos1":datos1,"datos2":datos2})
df

,datos1,datos2
0,7.180748,6.861376
1,7.701062,6.471774
2,7.271689,6.362365
3,6.720308,6.838444
4,7.015700,7.472108
5,6.390949,7.069059
6,7.293283,7.008203
7,7.009625,7.039661
8,6.959129,6.953915
9,7.007488,7.124110


3. Realice un análisis descriptivo para cada una de las pruebas: Media, Mediana, máximo,
mínimo, desviación estándar, cuantil 25% y cuantil 75%.

In [95]:
df.describe()

,datos1,datos2
count,58.000000,58.000000
mean,7.064586,6.971736
std,0.351427,0.392418
min,6.345376,6.305708
25%,6.790062,6.679989
50%,7.014305,6.953625
75%,7.287884,7.147781
max,7.929321,7.978883


4. Importe el siguiente módulo estadístico:
from scipy import stats
Aplique prueba de normalidad de Shapiro-Wilk para cada prueba ¿se cumple el supuesto
de normalidad con una confianza del 95%?

In [118]:
from scipy import stats

In [145]:
from scipy.stats import shapiro
a =shapiro(df["datos1"])
b =shapiro(df["datos2"])
print(a)
print(b)

ShapiroResult(statistic=np.float64(0.9796648210552779), pvalue=np.float64(0.437551106909689))
ShapiroResult(statistic=np.float64(0.972394972029578), pvalue=np.float64(0.20762311384861498))


si, si lo cumple, dado a que los valores obtenidos son mayores a 0,05

5. Aplique la prueba t Student para muestras paradas: use la función stats.ttest_rel
¿Se rechaza que el puntaje medio en ambas encuestas es igual con una confianza del 95%?

In [148]:
stats.ttest_rel(df["datos1"], df["datos2"])

TtestResult(statistic=np.float64(1.3322672154465922), pvalue=np.float64(0.18807455903589138), df=np.int64(57))

valores encima de 0.05

6. Aplique la prueba con el coeficiente de correlación de Kendall: función
stats.kendalltau
¿Se rechaza con una confianza del 95% que los puntajes de ambas encuestas no están
correlacionados?

In [149]:
stats.kendalltau(df["datos1"], df["datos2"])

SignificanceResult(statistic=np.float64(-0.0381125226860254), pvalue=np.float64(0.6725848547096187))

el primer valor esta debajo de 0.05

7. Aplique la prueba con el coeficiente de correlación de Spearman: función.spearmanr
¿Se rechaza con una confianza del 95% que los puntajes de ambas encuestas no están
correlacionados?

In [161]:
stats.spearmanr(df["datos1"], df["datos2"])

SignificanceResult(statistic=np.float64(-0.05232397182318743), pvalue=np.float64(0.6964771522067852))

el primer valor esta debajo de 0.05

8. Utilizando los códigos anteriores cree un paquete en Google Colab llamado comparacion:
import os
os.makedirs("comparacion", exist_ok=True)

In [172]:
import os
os.makedirs("comparacion", exist_ok=True)

9. Cree dos módulos:
 Uno para la prueba t Student: %%writefile comparacion/pruebat.py
 Otro para los coeficientes de correlación: %%writefile comparacion/cor.py

In [164]:
%%writefile comparacion/pruebat.py
stats.ttest_rel(df["datos1"], df["datos2"])


Writing comparacion/pruebat.py


FileNotFoundError: [Errno 2] No such file or directory: 'comparacion/pruebat.py'